## Copyright (C) 2020-2022 Aditya Shakya <adi1090x@gmail.com>
## Everyone is permitted to copy and distribute copies of this file under GNU-GPL3

## Colors configuration
colors:
  # Default colors
  primary:
    background: '#1D1F28'
    foreground: '#FDFDFD'

  # Normal colors
  normal:
    black:   '#1f1d1b'
    red:     '#F37F97'
    green:   '#5ADECD'
    yellow:  '#F2A272'
    blue:    '#8897F4'
    magenta: '#C574DD'
    cyan:    '#79E6F3'
    white:   '#FDFDFD'

  # Bright colors
  bright:
    black:   '#1f1d1b'
    red:     '#F37F97'
    green:   '#5ADECD'
    yellow:  '#F2A272'
    blue:    '#8897F4'
    magenta: '#C574DD'
    cyan:    '#79E6F3'
    white:   '#FDFDFD'
